"""empty message

Revision ID: 2fb2ed7e15a5
Revises: f81eb707a0ca
Create Date: 2016-01-02 14:25:23.995264

"""
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '2fb2ed7e15a5'
down_revision = 'f81eb707a0ca'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cat', sa.Text(), nullable=True),
    sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index('ix_document_search_vector', 'document', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_table('documenttest')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documenttest',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='document_pkey'),
    sa.UniqueConstraint('title', name='document_title_key')
    )
    op.drop_index('ix_document_search_vector', table_name='document')
    op.drop_table('document')
    ### end Alembic commands ###
